"""
certification_bootstrap_generator.py

Deterministic generator that creates the minimum required certification
readiness structure for a target project so that run_target_validation_precheck()
returns CERTIFICATION_READY_WITH_WARNINGS or better instead of
CERTIFICATION_NOT_READY due to missing structure alone.

Modes
-----
init          Create missing assets only; preserve everything that already exists.
safe-upgrade  Same as init: create missing, preserve existing (named differently
              to communicate intent in team workflows — "upgrade the incomplete
              structure safely without touching touched files").
overwrite     Create missing assets; overwrite assets that carry the
              _bootstrap_managed=true marker (i.e. files generated by THIS tool);
              preserve user-owned files that do not carry the marker.

All generated assets carry _bootstrap_managed=true so overwrite mode can
distinguish bootstrap-generated files from user-authored files.

Bootstrap scenario layout
-------------------------
Fixed proof dir name:  20000101_000000_bootstrap_baseline_scenario
    (matches _SCENARIO_DIR_RE = r"^(\\d{8}_\\d{6})_(.+)$" in certify_compare)
Fixed scenario_id:     bootstrap_baseline_scenario
Placeholder value:     0.5 (baseline = current = 0.5 → delta=0 → CERTIFIED_STABLE)

The bootstrap does not create system_snapshot/ because the compatibility
check only runs when that directory exists.

Public API
----------
run_certification_bootstrap(*, project_root, component, pf, mode) -> dict
CertificationBootstrapGenerator
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .certification_bootstrap_templates import (
    GENERATOR_VERSION,
    TEMPLATE_VERSION,
    make_actual_outcome,
    make_baseline_manifest,
    make_baseline_matrix,
    make_certification_target,
    make_diagnostic_metrics,
    make_diagnostic_scorecard,
    make_scenario_index,
    make_scenario_manifest,
)

# Deterministic proof dir: fixed 2000-01-01 timestamp, fixed scenario ID.
_BOOTSTRAP_SCENARIO_ID: str = "bootstrap_baseline_scenario"
_BOOTSTRAP_SCENARIO_NAME: str = "Bootstrap Baseline Scenario"
_BOOTSTRAP_PROOF_DIR_NAME: str = "20000101_000000_bootstrap_baseline_scenario"
_BOOTSTRAP_MANAGED_MARKER: str = "_bootstrap_managed"

_VALID_MODES: frozenset[str] = frozenset({"init", "safe-upgrade", "overwrite"})


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _iso_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=False), encoding="utf-8")


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _is_bootstrap_managed(path: Path) -> bool:
    """Return True iff path exists and its JSON content carries _bootstrap_managed=true."""
    if not path.is_file():
        return False
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return bool(data.get(_BOOTSTRAP_MANAGED_MARKER, False))
    except (OSError, ValueError, TypeError):
        pass
    return False


# ---------------------------------------------------------------------------
# Result dataclasses
# ---------------------------------------------------------------------------


@dataclass
class AssetStatus:
    path: str
    existed: bool
    action: str  # "created" | "preserved" | "skipped" | "overwritten" | "error"
    reason: str = ""


@dataclass
class BootstrapResult:
    mode: str
    project_root: str
    component: str
    generator_version: str = GENERATOR_VERSION
    template_version: str = TEMPLATE_VERSION
    assets: list[AssetStatus] = field(default_factory=list)
    structural_state: str = ""
    structural_ready: bool = False
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    created_count: int = 0
    preserved_count: int = 0
    skipped_count: int = 0
    overwritten_count: int = 0
    artifacts: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


class CertificationBootstrapGenerator:
    """Create or repair the minimum required certification file structure.

    Parameters
    ----------
    project_root:
        Directory whose certification readiness is being bootstrapped.
        certification_target.json will be created here; all other assets
        go under project_root/certification/.
    component:
        Logical component name written into generated artifacts (informational).
    pf:
        Proof folder for this bootstrap run.  Bootstrap reports are written
        under pf/bootstrap_reports/.
    mode:
        "init" | "safe-upgrade" | "overwrite"  (see module docstring).
    """

    def __init__(
        self,
        *,
        project_root: Path,
        component: str,
        pf: Path,
        mode: str = "init",
    ) -> None:
        if mode not in _VALID_MODES:
            raise ValueError(
                f"invalid_mode:{mode!r}  Allowed: {sorted(_VALID_MODES)}"
            )
        self.project_root = project_root.resolve()
        self.component = str(component).strip() or "unknown_component"
        self.pf = pf.resolve()
        self.mode = mode
        self._result = BootstrapResult(
            mode=mode,
            project_root=str(self.project_root),
            component=self.component,
        )

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def run(self) -> BootstrapResult:
        """Execute the bootstrap generation and return a result object."""
        cert_root = self.project_root / "certification"
        baseline_root = cert_root / "baseline_v1"
        scenario_proof_dir = cert_root / "_proof" / _BOOTSTRAP_PROOF_DIR_NAME
        project_name = self.project_root.name

        templates: dict[Path, dict] = {
            # Top-level contract
            self.project_root / "certification_target.json": make_certification_target(
                project_name=project_name,
                component=self.component,
            ),
            # Scenario registry
            cert_root / "scenario_index.json": make_scenario_index(
                component=self.component,
                scenario_id=_BOOTSTRAP_SCENARIO_ID,
                scenario_name=_BOOTSTRAP_SCENARIO_NAME,
            ),
            # Baseline aggregate files
            baseline_root / "baseline_manifest.json": make_baseline_manifest(
                component=self.component,
                project_name=project_name,
            ),
            baseline_root / "baseline_matrix.json": make_baseline_matrix(
                component=self.component,
                scenario_id=_BOOTSTRAP_SCENARIO_ID,
                scenario_name=_BOOTSTRAP_SCENARIO_NAME,
            ),
            baseline_root / "diagnostic_metrics.json": make_diagnostic_metrics(
                component=self.component,
            ),
            # Current scenario proof (bootstrap placeholder)
            scenario_proof_dir / "00_scenario_manifest.json": make_scenario_manifest(
                scenario_id=_BOOTSTRAP_SCENARIO_ID,
                scenario_name=_BOOTSTRAP_SCENARIO_NAME,
                component=self.component,
            ),
            scenario_proof_dir / "05_actual_outcome.json": make_actual_outcome(
                scenario_id=_BOOTSTRAP_SCENARIO_ID,
            ),
            scenario_proof_dir / "06_diagnostic_scorecard.json": make_diagnostic_scorecard(
                scenario_id=_BOOTSTRAP_SCENARIO_ID,
            ),
        }

        for path, payload in templates.items():
            self._write_asset(path, payload)

        self._assess_readiness()
        self._write_reports()
        return self._result

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _write_asset(self, path: Path, payload: dict[str, Any]) -> None:
        exists = path.is_file()
        is_managed = _is_bootstrap_managed(path) if exists else False

        action: str
        reason: str

        if not exists:
            # File is missing → create it regardless of mode
            try:
                _write_json(path, payload)
                action = "created"
                reason = f"missing_asset_created_{self.mode}_mode"
            except OSError as exc:
                action = "error"
                reason = f"write_error:{exc}"
                self._result.errors.append(f"write_error:{path}:{exc}")

        elif is_managed and self.mode == "overwrite":
            # File exists, is bootstrap-managed, and mode is overwrite → replace it
            try:
                _write_json(path, payload)
                action = "overwritten"
                reason = "bootstrap_managed_file_replaced_in_overwrite_mode"
                self._result.warnings.append(
                    f"overwrite_warning:bootstrap_managed_file_replaced:{path}"
                )
            except OSError as exc:
                action = "error"
                reason = f"write_error:{exc}"
                self._result.errors.append(f"write_error:{path}:{exc}")

        else:
            # File exists → preserve in all other cases
            if is_managed:
                reason = f"bootstrap_managed_file_preserved_{self.mode}_mode"
            else:
                reason = f"user_owned_file_preserved_{self.mode}_mode"
            action = "preserved"

        status = AssetStatus(path=str(path), existed=exists, action=action, reason=reason)
        self._result.assets.append(status)

        if action == "created":
            self._result.created_count += 1
            self._result.artifacts.append(str(path))
        elif action == "preserved":
            self._result.preserved_count += 1
        elif action == "skipped":
            self._result.skipped_count += 1
        elif action == "overwritten":
            self._result.overwritten_count += 1
            self._result.artifacts.append(str(path))

    def _assess_readiness(self) -> None:
        from .certification_target import run_target_validation_precheck

        try:
            precheck_pf = self.pf / "precheck_validate"
            target_result = run_target_validation_precheck(
                project_root=self.project_root,
                pf=precheck_pf,
            )
            self._result.structural_state = target_result.state
            self._result.structural_ready = target_result.state != "CERTIFICATION_NOT_READY"
            if target_result.errors:
                self._result.errors.extend(list(target_result.errors))
            if target_result.warnings:
                self._result.warnings.extend(list(target_result.warnings))
        except Exception as exc:  # noqa: BLE001
            self._result.structural_state = "PRECHECK_ERROR"
            self._result.structural_ready = False
            self._result.errors.append(f"precheck_error:{exc}")

    def _write_reports(self) -> None:
        report_dir = self.pf / "bootstrap_reports"
        report_dir.mkdir(parents=True, exist_ok=True)

        now_ts = _iso_now()

        summary: dict[str, Any] = {
            _BOOTSTRAP_MANAGED_MARKER: True,
            "generator_version": self._result.generator_version,
            "template_version": self._result.template_version,
            "timestamp_utc": now_ts,
            "mode": self._result.mode,
            "project_root": self._result.project_root,
            "component": self._result.component,
            "created_count": self._result.created_count,
            "preserved_count": self._result.preserved_count,
            "skipped_count": self._result.skipped_count,
            "overwritten_count": self._result.overwritten_count,
            "structural_state": self._result.structural_state,
            "structural_ready": self._result.structural_ready,
            "warnings": sorted(set(self._result.warnings)),
            "errors": sorted(set(self._result.errors)),
        }
        _write_json(report_dir / "00_bootstrap_summary.json", summary)

        asset_rows = [
            {
                "path": a.path,
                "existed": a.existed,
                "action": a.action,
                "reason": a.reason,
            }
            for a in self._result.assets
        ]
        _write_json(report_dir / "01_asset_actions.json", {"rows": asset_rows})

        md_lines = [
            "# Certification Bootstrap Report",
            "",
            f"- mode: {self._result.mode}",
            f"- component: {self._result.component}",
            f"- project_root: {self._result.project_root}",
            f"- structural_state: {self._result.structural_state}",
            f"- structural_ready: {str(self._result.structural_ready).lower()}",
            f"- created_count: {self._result.created_count}",
            f"- preserved_count: {self._result.preserved_count}",
            f"- skipped_count: {self._result.skipped_count}",
            f"- overwritten_count: {self._result.overwritten_count}",
            "",
            "## Asset Actions",
        ]
        for row in asset_rows:
            md_lines.append(f"- [{row['action']}] {row['path']}")
        if self._result.warnings:
            md_lines += ["", "## Warnings"]
            for w in sorted(set(self._result.warnings)):
                md_lines.append(f"- {w}")
        if self._result.errors:
            md_lines += ["", "## Errors"]
            for e in sorted(set(self._result.errors)):
                md_lines.append(f"- {e}")
        _write_text(report_dir / "02_bootstrap_report.md", "\n".join(md_lines) + "\n")

        self._result.artifacts.extend(
            [
                str(report_dir / "00_bootstrap_summary.json"),
                str(report_dir / "01_asset_actions.json"),
                str(report_dir / "02_bootstrap_report.md"),
            ]
        )


# ---------------------------------------------------------------------------
# Convenience function (used by CLI and tests)
# ---------------------------------------------------------------------------


def run_certification_bootstrap(
    *,
    project_root: Path,
    component: str,
    pf: Path,
    mode: str = "init",
) -> dict[str, Any]:
    """Run the bootstrap generator and return a plain-dict summary.

    Parameters
    ----------
    project_root : Path
        Directory to bootstrap certification readiness for.
    component : str
        Logical component label written into generated artifacts.
    pf : Path
        Proof folder for this bootstrap run.
    mode : str
        "init" | "safe-upgrade" | "overwrite"

    Returns
    -------
    dict with keys: summary, warnings, errors, artifacts
    """
    generator = CertificationBootstrapGenerator(
        project_root=project_root,
        component=component,
        pf=pf,
        mode=mode,
    )
    result = generator.run()
    return {
        "summary": {
            "mode": result.mode,
            "project_root": result.project_root,
            "component": result.component,
            "structural_state": result.structural_state,
            "structural_ready": result.structural_ready,
            "created_count": result.created_count,
            "preserved_count": result.preserved_count,
            "skipped_count": result.skipped_count,
            "overwritten_count": result.overwritten_count,
            "generator_version": result.generator_version,
            "template_version": result.template_version,
        },
        "warnings": sorted(set(result.warnings)),
        "errors": sorted(set(result.errors)),
        "assets": [
            {"path": a.path, "existed": a.existed, "action": a.action, "reason": a.reason}
            for a in result.assets
        ],
        "artifacts": result.artifacts,
    }
